Resize track shells horizontally
eclipsesource/perfetto pull request #109
Opened 2024-05-07 21:44 UTC by ALevansSamsung

#### What it does

Gives the user the ability to resize the column of track shells in the timeline.

#### How to test

1. Hover over to the right of timeline buttons till it changes the cursor (is 4px wide)
2. Drag the line to the right
3. UI should change accordingly

#### Media

https://github.com/eclipsesource/perfetto/assets/121060410/2892fd9f-2088-4367-b5bd-81416e309b15

2025-04-01 19:49 UTC, cdamus reviewed
Looking good! I have a specific comment in-line below and other feedback to offer on the Sokatoa PR.

2025-04-01 19:49 UTC, cdamus commented on ui/src/frontend/time_selection_panel.ts
> +    return m('.time-selection-panel', {
This is the third occurrence (so it seems to me) of this new addition of mouse handling. Can this be shared somehow instead of repeating it, for maintainability? Especially considering that we'll eventually need to port this onto the latest Perfetto upstream (unless they already have implemented resizable track headers themselves).

2025-04-02 20:53 UTC, cdamus requested changes, later dismissed
Thanks @ALevansSamsung for the changes so far. It's already better with track shell widths isolated per widget and remembered in the widget-state metadata. And resizing in the tracks area, too.

However, I did run into one problem, not sure how: I ended up with a negative track shell width as shown in the widget-state JSON below (I didn't hack that file; this happened entirely by mouse pointer)

```
"pinnedGroupCollapsed":false,"trackShellWidth":-100}
```

so you can see how on restoring the widget the Notes panel disappears out from behind its buttons but, oddly, the track shells remain:

https://github.com/user-attachments/assets/63cb09a5-3807-4596-9df9-7ab03cdd6e2c

Also, the checkboxes still appear in all the track shells when I change the width:

https://github.com/user-attachments/assets/f3b8555f-84fc-4f55-8f69-ecca6d9eb88c

Besides that, some comments old and new in-line (most barely more than nits).

2025-04-02 20:53 UTC, cdamus commented on ui/src/common/actions.ts
> +    if (isFinite(args.newWidth)) {
Finite is good (it covers those pesky NaNs), but what about zero or negative numbers? Should there be some minimum?

2025-04-02 20:53 UTC, cdamus commented on ui/src/frontend/notes_panel.ts
> +                (e.layerX +2) >= globals.state.trackShellWidth &&
The ±2 buffer should maybe be extracted to a constant? I think it counts as a "magic number."
At the very least, without whitespace between the sign and the number it looks like there isn't a mathematical operator in this expression. Especially in the -2 case.

Same comment everywhere this code is copied.

2025-04-02 20:53 UTC, cdamus commented on ui/src/frontend/track_group_panel.ts
> +          onmousemove: (e: PerfettoMouseEvent)=>{
Fourth occurrence of the same code. 😉

2025-04-02 20:56 UTC, ALevansSamsung commented on ui/src/frontend/track_group_panel.ts
> +          onmousemove: (e: PerfettoMouseEvent)=>{
I've been working all day to factor it out 🙃

2025-04-02 20:58 UTC, cdamus commented on ui/src/frontend/track_group_panel.ts
> +          onmousemove: (e: PerfettoMouseEvent)=>{
Ah, sorry, I jumped the gun. I'll wait to review again when asked!

2025-04-02 21:01 UTC, ALevansSamsung commented on ui/src/frontend/track_group_panel.ts
> +          onmousemove: (e: PerfettoMouseEvent)=>{
I realized rather than copy it on everything's right border I could just add it to the page element and check whether we're at the same X as the trackShellWidth.

2025-04-03 14:09 UTC, ALevansSamsung commented
> Thanks @ALevansSamsung for the changes so far. It's already better with track shell widths isolated per widget and remembered in the widget-state metadata. And resizing in the tracks area, too.
> 
> However, I did run into one problem, not sure how: I ended up with a negative track shell width as shown in the widget-state JSON below (I didn't hack that file; this happened entirely by mouse pointer)
> 
> ```
> "pinnedGroupCollapsed":false,"trackShellWidth":-100}
> ```
> 
> so you can see how on restoring the widget the Notes panel disappears out from behind its buttons but, oddly, the track shells remain:
> 
>  CleanShot.2025-04-02.at.16.40.37.mp4 
> Also, the checkboxes still appear in all the track shells when I change the width:
> 
>  CleanShot.2025-04-02.at.16.51.07.mp4 
> Besides that, some comments old and new in-line (most barely more than nits).

I think my latest commit should fix these.

2025-04-03 21:01 UTC, cdamus reviewed
Very nice! When it works, the resizing is now very reliable, smooth, and free of checkboxes 😀 

However, it only works for the first timeline widget that I open. The second one, nothing. But if I close both widgets and open the second one again, then I can resize the track shells in it.

I don't know whether this is a problem in the Perfetto code or in the integration in the host application, so I won't request changes here. But something's not right.

https://github.com/user-attachments/assets/e64478ab-a156-418e-bd73-eeb04972bf12

2025-04-03 22:40 UTC, ALevansSamsung commented
Tested with multiple Perfetto's and fixed it up

2025-04-04 13:07 UTC, cdamus approved these changes
Works great! Thanks. Just one nit that I wouldn't need another look at.

2025-04-04 13:07 UTC, cdamus commented on ui/src/frontend/viewer_page.ts
> +  resizeTrackShell(e: MouseEvent): void {
nit: this method probably doesn't need to be public API

2025-04-09 20:53 UTC, wpaul-samsung commented
@ALevansSamsung What's the status of this?

2025-04-09 22:02 UTC, csteinberg-samsung approved these changes
Works for me

2025-04-09 22:06 UTC, merged