Design/show timeline behind expanded track groups
eclipsesource/perfetto pull request #122
Opened 2024-07-01 16:08 UTC by ALevansSamsung

#### What it does

Show summary tracks when track groups are expanded rather then dead space

2024-07-10 17:44 UTC, cdamus requested changes
Looks as advertised: the grid is always continuous and the summary track (when present) always shows.

But the selection behaviour of groups is wonky. It requires multiple clicks to deselect and even then, sometimes it doesn't deselect all members of the group. Moreover, when initially drawing the selection, if it only overlaps some of the tracks of an expanded group the selection nonetheless takes in all of the other tracks in that group that I didn't draw the mouse over. See the very beginning of this screen grab for that selection rectangle behaviour.

![CleanShot 2024-07-10 at 13 39 14](https://github.com/eclipsesource/perfetto/assets/1615558/aec3c6eb-4d91-4d86-a8a6-87dc0ab5e0ba)

2024-07-11 12:43 UTC, cdamus reviewed
It's not clear to me what has changed ... the selection state of a group as controlled at the group level is still wildly inconsistent.

On the matter of the initial selection range, on reflection I think there's no issue there: the rubber-band is clearly previewing that the whole group will be selected when dragging the pointer over a part of it, so I think that's a clear communication to the user of what will happen.

![CleanShot 2024-07-11 at 08 40 18](https://github.com/eclipsesource/perfetto/assets/1615558/6729cce8-7a44-4be9-a5bf-8001d33e471d)

2024-07-11 14:57 UTC, ALevansSamsung commented
> It's not clear to me what has changed ... the selection state of a group as controlled at the group level is still wildly inconsistent.

My latest change was suppose to make the checkboxes select and deselect children recursively.  I'll test again.

2024-07-11 15:04 UTC, ALevansSamsung commented
Ok, it seems that scrolling over a track group and then also its children causes some tracks to be saved as selected multiple times therefore when they are deselected they are only deselecting the one iteration.

2024-07-11 15:11 UTC, cdamus commented
> Ok, it seems that scrolling over a track group and then also its children causes some tracks to be saved as selected multiple times therefore when they are deselected they are only deselecting the one iteration.

Oh yeah, that makes sense. In fact, my GIF I think captured this? I notice that the tracks in the "Memory Usage" group that had sticky selection were the ones that my mouse pointer actually dragged over. Others that were included in the extended selection rubber-band were not so sticky.

2024-07-11 17:51 UTC, cdamus approved these changes
Yup, that did it. Thanks!

2024-07-11 17:51 UTC, cdamus commented on ui/src/frontend/panel_container.ts
> +    const tracks = new Set<string>();
Nice! That's so simple 😀

2024-10-21 21:09 UTC, merged